config/routes.rb
Rails.application.routes.draw do
    root to: 'waterscapes#index'
    resources :waterscapes
    
    get 'signup' , to: 'users#new'
    resources :users do
        member do
            get :liker
            get :liked
        end
        collection do
            get :search
        end
    end
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :waterscape
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :waterscapes, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked, through: :likes, source: :user
    has_many :liker, through: :likes, source: :waterscape
    
    # ---like unlike---
    def like(waterscape)
      self.likes.find_or_create_by(waterscape_id: waterscape.id)
    end
    
    def unlike(waterscape)
      like = self.likes.find_by(waterscape_id: waterscape.id)
      like.destroy if like
    end
    
    def liking?(waterscape)
      self.liker.include?(waterscape)
    end
end

app/models/waterscape.rb
class Waterscape < ApplicationRecord
  belongs_to :user
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
        @count_waterscapes = user.waterscapes.count
        @count_liker = user.liker.count
        @count_liked = user.liked.count
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_logged_in

  def create
    waterscape = Waterscape.find(params[:waterscape_id])
    current_user.like(waterscape)
    flash[:success] = 'お気に入り登録しました。'
    redirect_to root_url
  end

  def destroy
    waterscape = Waterscape.find(params[:waterscape_id])
    current_user.unlike(waterscape)
    flash[:success] = 'お気に入り登録を解除しました。'
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index, :show]
  before_action :correct_user_changes_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_waterscapes = @user.waterscapes.page(params[:page]).per(12)
    @likers = @user.liker.page(params[:page]).per(12)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] ='ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] ='ユーザ情報を編集しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ情報の編集に失敗しました'
      render :edit
    end
  end
  
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:success] = "ユーザアカウントを削除しました"
      redirect_to root_url
  end
  
  def likers
    @user = User.find(params[:id])
    @likers = @user.liker
    counts(@user)
  end
  
  def likeds
    @user = User.find(params[:id])
    @liked = @user.liked
    counts(@user)
  end

  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user_changes_user
    @user = User.find(params[:id])
    unless @user == current_user
        redirect_to root_url
    end
  end
  
end

app/controllers/waterscapes_controller.rb
class WaterscapesController < ApplicationController
    before_action :require_logged_in, only: [:new, :create]
    before_action :correct_user, only: [:edit, :update, :destroy]
    
    def index
        @waterscapes = Waterscape.all.page(params[:page]).per(24)
    end
    
    def show
        @waterscape = Waterscape.find(params[:id])
    end
    
    def new
        @waterscape = current_user.waterscapes.new
    end
    
    def create
        if params[:waterscape].present?
            @waterscape = current_user.waterscapes.new(waterscape_params)
            if @waterscape.save
                flash[:success] = "投稿に成功しました"
                redirect_to root_url
            else
                flash.now[:danger] = "投稿に失敗しました"
                render :new
            end
        else
            render :new
        end
    end
    
    def edit
        @waterscape = Waterscape.find(params[:id])
    end
    
    def update
        @waterscape = Waterscape.find(params[:id])
        if @waterscape.update(waterscape_params)
            flash[:success]= "編集されました"
            redirect_to @waterscape
        else
            flash[:danger] = "編集に失敗しました"
            render :edit
        end
    end
    
    def destroy
        @waterscape = Waterscape.find(params[:id])
        @waterscape.destroy
        flash[:success] = "画像を削除しました"
        redirect_to root_url
    end
    
    private
    
    def waterscape_params
        params.require(:waterscape).permit(:image)
    end
    
    def correct_user
        @waterscape = current_user.waterscapes.find_by(id: params[:id])
        unless @waterscape
            redirect_to root_url
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom bg-dark px-1 py-3">
    <div id="copyright" class="container">
        <p class="text-center mb-0 text-light">Copyright ©︎ 2021 ohno issei.<br> All Right Reserved</p>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Suikei</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navmenu" aria-controls="navmenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-right justify-content-end" id="navmenu">
            <ul class="navbar-nav">
                <% if logged_in? %>
                    <li class="nav-item"></i><%= link_to current_user.name, user_path(current_user), class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, data:{ confirm:'ロウグアウトしてよろしいですか？' }, class: 'nav-link' %></li>
                <% else %>
                    <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Suikei</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div id="main-contents"class="container mt-1">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <div class="push"></div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/likes/_like_button.html.erb
<% if logged_in? %>
  <% if current_user.liking?(waterscape) %>
      <%= form_with(model: current_user.likes.find_by(waterscape_id: waterscape.id), local: true, method: :delete) do |f| %>
        <%= hidden_field_tag :waterscape_id, waterscape.id %>
        <%= f.submit 'Like', class: 'btn btn-primary btn-sm' %>
      <% end %>
  <% else %>
      <%= form_with(model: current_user.likes.build, local: true) do |f| %>
        <%= hidden_field_tag :waterscape_id, waterscape.id %>
        <%= f.submit 'Like', class: 'btn btn-secondary btn-sm' %>
      <% end %>
  <% end %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="text-center">
    <h1>ユーザ編集 : <%= @user.name %></h1>
</div>
<div class='row'>
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :name,'Name' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :email,'Email' %>
                <%= f.email_field :email, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :password,'Password' %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :password_confirmation,'Confirmation' %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            
            <%= f.submit 'Edit',class:'btn btn-primary btn-block' %>
            <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>
<ul>
    <% @users.each do |user| %>
        <li><%=link_to user.id, user %> : <%= user.name %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<div class="text-center">
    <h1>ユーザ登録</h1>
</div>
<div class='row'>
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :name,'Name' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :email,'Email' %>
                <%= f.email_field :email, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :password,'Password' %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :password_confirmation,'Confirmation' %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            
            <%= f.submit 'Sign up',class:'btn btn-primary btn-block' %>
            <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h1>ユーザ詳細</h1>
<div>
    <div class="pb-3 border-bottom">
        <h4>Name : <%= @user.name %></h4>
        <h4>Email : <%= @user.email %></h4>
        <div class="text-right">
            <% if current_user == @user %>
                <%= link_to 'ユーザアカウント編集' , edit_user_path(@user), class: "btn btn-primary" %>
                <%= link_to 'ユーザアカウント削除', @user, method: :delete, data: { confirm: 'アカウントを削除しますがよろしいですか' }, class: 'btn btn-danger' %>
            <% end %>
        </div>
    </div>

    <div class="pb-3">
        <div class="pt-3">
            <h4>投稿画像<span class="badge badge-pill badge-secondary"><%= @count_waterscapes %></span></h4>
            <%= render 'waterscapes/waterscapes', waterscapes: @user_waterscapes %>
        </div>
        <div class="pt-3">
            <h4>お気に入り水景<span class="badge badge-pill badge-secondary"><%= @count_liker %></span></h4>
            <%= render 'waterscapes/waterscapes', waterscapes: @likers %>
        </div>
    </div>
    <div class="p-1 pt-2">
        <%= link_to '新規投稿' , new_waterscape_path, class: "btn btn-primary" %>
        <%= link_to 'トップへ' , waterscapes_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/waterscapes/_waterscapes.html.erb
<div class="row p-1 pb-3">
    <% waterscapes.each do |waterscape| %>
        <div class="p-1 col-sm-2">
            <p><%= waterscape.id%></p>
            <div><%= link_to image_tag(waterscape.image.url, width: '100%',alt:'水景画像'), waterscape %></div>
            <!--like button-->
            <div class="mt-1"><%= render 'likes/like_button', waterscape: waterscape %></div>
        </div>
    <% end %>
</div>
<div class="pt-3 pb-3 border-bottom border-secondary border-5"><%= paginate waterscapes %></div>

app/views/waterscapes/edit.html.erb
<div class="text-center">
    <h1>編集ページ</h1>
</div>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @waterscape, local:true) do |f| %>
            <div class="form-group">
                <%= f.label :image,'画像' %>
                <%= f.file_field :image, class: 'form-control' %>
            </div>
            <%= f.submit '更新' %>
        <% end %>
    </div>
</div>

app/views/waterscapes/index.html.erb
<%= render 'waterscapes/waterscapes', waterscapes: @waterscapes %>
<div class="p-1 pt-3">
    <%= link_to '新規投稿' , new_waterscape_path, class: "btn btn-primary" %>
    <%= link_to 'ユーザ一覧', users_url, class: "btn btn-primary" %>
</div>

app/views/waterscapes/new.html.erb
<div class="text-center">
    <h1>新規投稿</h1>
</div>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @waterscape, local:true) do |f| %>
            <div class="form-group">
                <%= f.label :image,'Image' %>
                <%= f.file_field :image, class: 'form-control' %>
            </div>
            <%= f.submit '投稿',class: 'btn btn-block btn-primary' %>
        <% end %>
    </div>
</div>

app/views/waterscapes/show.html.erb
<h1>水景詳細</h1>
<div>
    <p class="mb-1">id : <%= @waterscape.id %></p>
    <p class="mb-1">投稿者 : <%= @waterscape.user.name %></p>
    <p class="mb-1">投稿日時 : <%= @waterscape.created_at %></p>
</div>
<div class="row p-1 pb-3 border-bottom">
    <div class="col-sm-12"><%= image_tag @waterscape.image.url, width: '100%',alt:'水景画像' %></div>
</div>
<div class="p-1 pt-2">
    <% if current_user == @waterscape.user %>
        <%= link_to '編集' , edit_waterscape_path(@waterscape), class: 'btn btn-secondary' %>
        <%= link_to '削除', @waterscape, method: :delete, data: { confirm: '削除しますがよろしいですか' }, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to 'トップへ' , waterscapes_path, class: "btn btn-primary" %>
</div>